apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datavolve-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: datavolve-volume
  storageClassName: ""
  selector:
    matchLabels:
      usage: datavolve