apiVersion: v1
kind: PersistentVolume
metadata:
  name: datavolve-volume
  labels:
    usage: datavolve
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: blob.csi.azure.com
    volumeHandle: MC_myAKSResourceGroup0472af_myAKSCluster0472af_canadacentral#sadatavolveaccount#datavolve-container
    volumeAttributes:
      containerName: datavolve-container
      storageAccount: sadatavolveaccount
      azureStorageAuthType: MSI
      azureStorageIdentityClientID: 261ac719-91e0-438d-aebc-7e5687c074fb

# bebdf0a7-be7a-48ab-90e8-dfcb0fad3c0b


