apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datavolve-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi-managed-identity
  volumeName: datavolve-volume
  resources:
    requests:
      storage: 5Gi