apiVersion: v1
kind: PersistentVolume
metadata:
  name: workload-1-volume
  labels:
    usage: workload-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: blob.csi.azure.com
    volumeHandle: MC_myAKSResourceGroup0472af_myAKSCluster0472af_canadacentral#saworkload1account#workload-1-container
    volumeAttributes:
      containerName: workload-1-container
      storageAccount: saworkload1account
      azureStorageAuthType: MSI
      azureStorageIdentityClientID: {REPLACE_WITH_MSI_CLIENT_ID}


