# filepath: /f:/Projects/AKS-lab/azure-storage-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datavolve-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azureblob-fuse-premium  # Use the default StorageClass
  volumeName: datavolve-volume
  resources:
    requests:
      storage: 5Gi