apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workload-1-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: workload-1-volume
  storageClassName: ""
  selector:
    matchLabels:
      usage: workload-1