apiVersion: batch/v1
kind: Job
metadata:
  name: datavolve-job
spec:
  template:
    spec:
      serviceAccountName: uami-service-account  # Add this line
      containers:
      - name: datavolve-container
        image: acrdatavolvedemo2.azurecr.io/bccsoftware/datavolve:latest
        command: ["/bin/bash", "-c"]
        args: ["sleep infinity"]
      restartPolicy: Never
  backoffLimit: 4