apiVersion: batch/v1
kind: Job
metadata:
  name: workload-1-job
spec:
  template:
    spec:
      containers:
      - name: workload-1-container
        image: acrakslabworkload1.azurecr.io/workload1repo/workload-1-image:latest
        command: ["/bin/bash", "-c"]
        args: ["mkdir -p /mnt/workload-1-volume/RESULTS && ls -R /mnt/workload-1-volume > /mnt/workload-1-volume/RESULTS/workload-1-results.txt"]
        volumeMounts:
        - name: workload-1-volume
          mountPath: /mnt/workload-1-volume
          readOnly: false
      restartPolicy: Never
      volumes:
      - name: workload-1-volume
        persistentVolumeClaim:
          claimName: workload-1-pvc
  backoffLimit: 4